name: CI Pipeline

on:
  push:
    branches:
      - "feature/**"
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  backend-lint-and-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm test -- --ci

  backend-e2e-tests:
    runs-on: ubuntu-latest
    needs: backend-lint-and-unit-tests
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'))
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - run: npm ci
      - run: npm run test:e2e -- --ci

  # frontend-lint-and-unit-tests:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: frontend
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "npm"
  #         cache-dependency-path: frontend/package-lock.json

  #     - run: npm ci
  #     - run: npm run lint
  #     - run: npm run format:check
  #     - run: npm test -- --ci

  # frontend-e2e-tests:
  #   runs-on: ubuntu-latest
  #   needs: frontend-lint-and-unit-tests
  #   if: >
  #     github.event_name == 'pull_request' ||
  #     (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'))
  #   defaults:
  #     run:
  #       working-directory: frontend
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "npm"
  #         cache-dependency-path: frontend/package-lock.json

  #     - run: npm ci
  #     - run: npm run test:e2e -- --ci

  docker-build:
    runs-on: ubuntu-latest
    needs: backend-e2e-tests

    if: >
      github.event_name == 'push' &&
      (startsWith(github.ref, 'refs/heads/develop') ||
       startsWith(github.ref, 'refs/heads/main'))

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: backend:ci

      # - uses: docker/build-push-action@v6
      #   with:
      #     context: ./frontend
      #     file: ./frontend/Dockerfile
      #     push: false
      #     tags: frontend:ci
